//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReportApplication.Models.Timetable
{

    public partial class AppRoleClaims : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Guid fRoleId;
        public Guid RoleId
        {
            get { return fRoleId; }
            set { SetPropertyValue<Guid>(nameof(RoleId), ref fRoleId, value); }
        }
        string fClaimType;
        [Size(SizeAttribute.Unlimited)]
        public string ClaimType
        {
            get { return fClaimType; }
            set { SetPropertyValue<string>(nameof(ClaimType), ref fClaimType, value); }
        }
        string fClaimValue;
        [Size(SizeAttribute.Unlimited)]
        public string ClaimValue
        {
            get { return fClaimValue; }
            set { SetPropertyValue<string>(nameof(ClaimValue), ref fClaimValue, value); }
        }
    }

}
