//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReportApplication.Models.Timetable
{

    public partial class AppRoles : XPLiteObject
    {
        Guid fId;
        [Key(true)]
        public Guid Id
        {
            get { return fId; }
            set { SetPropertyValue<Guid>(nameof(Id), ref fId, value); }
        }
        string fName;
        [Size(SizeAttribute.Unlimited)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fNormalizedName;
        [Size(SizeAttribute.Unlimited)]
        public string NormalizedName
        {
            get { return fNormalizedName; }
            set { SetPropertyValue<string>(nameof(NormalizedName), ref fNormalizedName, value); }
        }
        string fConcurrencyStamp;
        [Size(SizeAttribute.Unlimited)]
        public string ConcurrencyStamp
        {
            get { return fConcurrencyStamp; }
            set { SetPropertyValue<string>(nameof(ConcurrencyStamp), ref fConcurrencyStamp, value); }
        }
        string fDescription;
        [Size(200)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
