//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReportApplication.Models.Timetable
{

    public partial class AppUserTokens : XPLiteObject
    {
        Guid fUserId;
        [Key(true)]
        public Guid UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<Guid>(nameof(UserId), ref fUserId, value); }
        }
        string fLoginProvider;
        [Size(SizeAttribute.Unlimited)]
        public string LoginProvider
        {
            get { return fLoginProvider; }
            set { SetPropertyValue<string>(nameof(LoginProvider), ref fLoginProvider, value); }
        }
        string fName;
        [Size(SizeAttribute.Unlimited)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fValue;
        [Size(SizeAttribute.Unlimited)]
        public string Value
        {
            get { return fValue; }
            set { SetPropertyValue<string>(nameof(Value), ref fValue, value); }
        }
    }

}
