//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ReportApplication.Models.Timetable
{

    [Persistent(@"__EFMigrationsHistory")]
    public partial class P__EFMigrationsHistory : XPLiteObject
    {
        string fMigrationId;
        [Key]
        [Size(150)]
        public string MigrationId
        {
            get { return fMigrationId; }
            set { SetPropertyValue<string>(nameof(MigrationId), ref fMigrationId, value); }
        }
        string fProductVersion;
        [Size(32)]
        public string ProductVersion
        {
            get { return fProductVersion; }
            set { SetPropertyValue<string>(nameof(ProductVersion), ref fProductVersion, value); }
        }
    }

}
